ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

# Development:
RUN apt-get -y update && apt-get -y upgrade && apt-get install -y ffmpeg
COPY ./requirements.txt .
RUN pip install -r requirements.txt


COPY . /app


# production:
# RUN pip install --no-cache-dir -r requirements.txt

RUN echo "alias python='python3'" >> /root/.bashrc

CMD ["bash"]
